name: Test csvw-check
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  test_in_environments:
    runs-on: ${{ inputs.os }}
    container:
      image: sbtscala/scala-sbt:graalvm-ce-22.3.3-b1-java17_1.10.7_3.6.3
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile
        run: sbt compile

      - name: Run tests
        run: sbt test

      - name: Archive test results from xml files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.os }} test results
          path: |
            target/test-reports/*.xml

  publish_test_results:
    needs: [test_in_environments]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.os }} test results

      - name: Publish Unit & Behave Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Unit and Cucumber Test Results
          junit_files: |
            **/*.xml
